apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"jenkins","namespace":"jenkins"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"app":"jenkins"},"type":"NodePort"}}
  creationTimestamp: null
  name: jenkins
  selfLink: /api/v1/namespaces/jenkins/services/jenkins
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  sessionAffinity: None
  type: NodePort
